import type { Metadata } from "next";
// Self-hosted fonts (bundled with the project, no download from Google at dev time)
import "@fontsource-variable/inter";
import "@fontsource-variable/playfair-display";
import "./globals.css";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
